[package]
name = "git-latexdiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.16"
which = "4.3.0"
crossterm = "0.25.0"
clap = { version='4', features = ['derive']}
skim = "0.10.2"